### ISSUE TITLE
gameserver启动报错，但可以看到橙子了，点击Test Game Server没有反应

### ISSUE THREAD

**Issue by dpzone** [NetEase/pomelo-cn#100]
1、启动webserver正常，启动gameserver有如下错误，是因为node的安装路径中有空格？天呐。。。是默认安装，没看到可以自定义安装路径啊。。。。：
C:\Program Files\nodejs\helloWorld\game-server>pomelo start
[32m[2013-03-09 16:33:59.683] [INFO] \node_modules\pomelo\lib\application.js - [39mapplication inited: "master-server-1"
[2013-03-09 16:33:59.683] [INFO] \node_modules\pomelo\lib\application.js - application inited: "master-server-1"

[32m[2013-03-09 16:34:01.386] [INFO] console - [39minfo: 'socket.io started'
[2013-03-09 16:34:01.386] [INFO] console - info: 'socket.io started'

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)
[32m[2013-03-09 16:34:01.386] [INFO] \node_modules\pomelo\lib\master\starter.js - [39mExecuting cd C:\Program Files\nodejs\helloWorld\game-server && node  C:\Program Files\nodejs\helloWorld\game-server\app.js env=development  id=connector-server-1  host=127.0.0.1  port=3150  wsPort=3010  serverType=connector  locally
[2013-03-09 16:34:01.386] [INFO] \node_modules\pomelo\lib\master\starter.js - Executing cd C:\Program Files\nodejs\helloWorld\game-server && node  C:\Program Files\nodejs\helloWorld\game-server\app.js env=development  id=connector-server-1  host=127.0.0.1  port=3150  wsPort=3010  serverType=connector  locally

[32m[2013-03-09 16:34:01.767] [INFO] \node_modules\pomelo\node_modules\pomelo-admin\lib\consoleService.js - [39mtry to connect master: "master", "127.0.0.1", 3005
[32m[2013-03-09 16:34:02.210] [INFO] console - [39m
module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)

[2013-03-09 16:34:01.767] [INFO] \node_modules\pomelo\node_modules\pomelo-admin\lib\consoleService.js - [31m[2013-03-09 16:34:02.210] [ERROR] console - [39mFAILED TO RUN, return code: 1
[31m[2013-03-09 16:34:02.213] [ERROR] console - [39m Caught exception: TypeError: undefined is not a function
    at starter.localrun (C:\Program Files\nodejs\helloWorld\game-server\node_modules\pomelo\lib\master\starter.js:136:7)
    at ChildProcess.spawnProcess (C:\Program Files\nodejs\helloWorld\game-server\node_modules\pomelo\lib\master\starter.js:191:7)
    at ChildProcess.EventEmitter.emit (events.js:99:17)
    at Process._handle.onexit (child_process.js:678:10)
try to connect master: "master", "127.0.0.1", 3005

[32m[2013-03-09 16:34:02.230] [INFO] \node_modules\pomelo\lib\application.js - [39m"master-server-1" enter after start...
[32m[2013-03-09 16:34:02.231] [INFO] \node_modules\pomelo\lib\application.js - [39m"master-server-1" finish start
[2013-03-09 16:34:02.210] [INFO] console - 
module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:245:9)

[2013-03-09 16:34:02.210] [ERROR] console - FAILED TO RUN, return code: 1
[2013-03-09 16:34:02.213] [ERROR] console -  Caught exception: TypeError: undefined is not a function
    at starter.localrun (C:\Program Files\nodejs\helloWorld\game-server\node_modules\pomelo\lib\master\starter.js:136:7)
    at ChildProcess.spawnProcess (C:\Program Files\nodejs\helloWorld\game-server\node_modules\pomelo\lib\master\starter.js:191:7)
    at ChildProcess.EventEmitter.emit (events.js:99:17)
    at Process._handle.onexit (child_process.js:678:10)

[2013-03-09 16:34:02.230] [INFO] \node_modules\pomelo\lib\application.js - "master-server-1" enter after start...
[2013-03-09 16:34:02.231] [INFO] \node_modules\pomelo\lib\application.js - "master-server-1" finish start

2、访问http://127.0.0.1:3001/index.html可以看到大橙子，点击Test Game Server没有反应，用IE 8才看到有个错误：
网页错误详细信息

消息: 'pomelo' 为空或不是对象
行: 22
字符: 9
代码: 0
URI: http://127.0.0.1:3001/index.html

**Comment by py8765** [comment]
IE8可能不支持，你所用的pomelo是什么版本。
