### ISSUE TITLE
game server 运行出错

### ISSUE THREAD

**Issue by tieqixia** [NetEase/pomelo-cn#101]
运行环境
1. 操作系统：mac os x 10.8.2
2. nodejs版本：v0.8.22
3. pomelo版本：0.3.1

操作：
1. 初始化目录：pomelo init helloWord
2. 下载依赖包：cd helloWord && sh npm-install.sh
3. 启动game服务器：cd game-server && pomelo start
然后系统报错，错误信息如下：
[2013-03-09 18:23:34.474] [INFO] /node_modules/pomelo/lib/application.js - application inited: "master-server-1"

[2013-03-09 18:23:34.739] [INFO] console - info: 'socket.io started'

[2013-03-09 18:23:34.741] [INFO] /node_modules/pomelo/lib/master/starter.js - Executing cd /Users/pulee/Work/game/helloPomelo/game-server && node  /Users/pulee/Work/game/helloPomelo/game-server/app.js env=development  id=connector-server-1  host=127.0.0.1  port=3150  clientPort=3010  frontend=true  serverType=connector  locally

[2013-03-09 18:23:34.747] [INFO] /node_modules/pomelo/node_modules/pomelo-admin/lib/consoleService.js - try to connect master: "master", "127.0.0.1", 3005

[2013-03-09 18:23:34.842] [INFO] /node_modules/pomelo/lib/application.js - "master-server-1" enter after start...

[2013-03-09 18:23:34.842] [INFO] /node_modules/pomelo/lib/application.js - "master-server-1" finish start

[2013-03-09 18:23:34.914] [INFO] console - [2013-03-09 18:23:34.899] [INFO] /node_modules/pomelo/lib/application.js - application inited: "connector-server-1"

[2013-03-09 18:23:35.232] [INFO] console - 

[2013-03-09 18:23:35.233] [INFO] console - module.js:478

[2013-03-09 18:23:35.233] [INFO] console -     throw err;
          ^

[2013-03-09 18:23:35.235] [INFO] console - SyntaxError: /Users/pulee/Work/game/helloPomelo/game-server/config/serverProtos.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:475:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at new Protobuf (/Users/pulee/Work/game/helloPomelo/game-server/node_modules/pomelo/lib/components/protobuf.js:18:40)
    at module.exports (/Users/pulee/Work/game/helloPomelo/game-server/node_modules/pomelo/lib/components/protobuf.js:6:10)
    at Object.Application.load (/Users/pulee/Work/game/helloPomelo/game-server/node_modules/pomelo/lib/application.js:141:17)
    at Object.module.exports.loadDefaultComponents (/Users/pulee/Work/game/helloPomelo/game-server/node_modules/pomelo/lib/util/appUtil.js:35:11)

[2013-03-09 18:23:35.239] [ERROR] console - FAILED TO RUN, return code: 1

[2013-03-09 18:23:35.243] [ERROR] console -  Caught exception: TypeError: undefined is not a function
    at starter.localrun (/Users/pulee/Work/game/helloPomelo/game-server/node_modules/pomelo/lib/master/starter.js:136:7)
    at ChildProcess.spawnProcess (/Users/pulee/Work/game/helloPomelo/game-server/node_modules/pomelo/lib/master/starter.js:191:7)
    at ChildProcess.EventEmitter.emit (events.js:99:17)
    at Process._handle.onexit (child_process.js:678:10)

**Comment by py8765** [comment]
config文件夹下面的serverProtos.json，clientProtos.json和dictionary.json文件都加上{ }
