### ISSUE TITLE
game-server启动报错~

### ISSUE THREAD

**Issue by peiweippww** [NetEase/pomelo-cn#103]
安装完成后，执行pomelo start报错。我的node版本是 0.8.21

[2013-03-11 13:48:38.719] [INFO] /node_modules/pomelo/lib/application.js - application inited: "master-server-1"

[2013-03-11 13:48:39.002] [INFO] console - info: 'socket.io started'

[2013-03-11 13:48:39.004] [INFO] /node_modules/pomelo/lib/master/starter.js - Executing cd /data/work/peiwei/pomelo_test/game-server && node  /data/work/peiwei/pomelo_test/game-server/app.js env=development  id=connector-server-1  host=127.0.0.1  port=3150  clientPort=3010  frontend=true  serverType=connector  locally

[2013-03-11 13:48:39.010] [INFO] /node_modules/pomelo/node_modules/pomelo-admin/lib/consoleService.js - try to connect master: "master", "127.0.0.1", 3005

[2013-03-11 13:48:39.089] [INFO] /node_modules/pomelo/lib/application.js - "master-server-1" enter after start...

[2013-03-11 13:48:39.089] [INFO] /node_modules/pomelo/lib/application.js - "master-server-1" finish start

[2013-03-11 13:48:39.135] [INFO] console - [2013-03-11 13:48:39.125] [INFO] /node_modules/pomelo/lib/application.js - application inited: "connector-server-1"

[2013-03-11 13:48:39.481] [INFO] console - 

[2013-03-11 13:48:39.482] [INFO] console - module.js:478

[2013-03-11 13:48:39.482] [INFO] console -     throw err;
          ^

[2013-03-11 13:48:39.484] [INFO] console - SyntaxError: /data/work/peiwei/pomelo_test/game-server/config/serverProtos.json: Unexpected end of input
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:475:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at new Protobuf (/data/work/peiwei/pomelo_test/game-server/node_modules/pomelo/lib/components/protobuf.js:18:40)
    at module.exports (/data/work/peiwei/pomelo_test/game-server/node_modules/pomelo/lib/components/protobuf.js:6:10)
    at Object.Application.load (/data/work/peiwei/pomelo_test/game-server/node_modules/pomelo/lib/application.js:141:17)
    at Object.module.exports.loadDefaultComponents (/data/work/peiwei/pomelo_test/game-server/node_modules/pomelo/lib/util/appUtil.js:35:11)

[2013-03-11 13:48:39.488] [ERROR] console - FAILED TO RUN, return code: 1

[2013-03-11 13:48:39.491] [ERROR] console -  Caught exception: TypeError: undefined is not a function
    at starter.localrun (/data/work/peiwei/pomelo_test/game-server/node_modules/pomelo/lib/master/starter.js:136:7)
    at ChildProcess.spawnProcess (/data/work/peiwei/pomelo_test/game-server/node_modules/pomelo/lib/master/starter.js:191:7)
    at ChildProcess.EventEmitter.emit (events.js:99:17)
    at Process._handle.onexit (child_process.js:678:10)

**Comment by peiweippww** [comment]
此问题貌似已经解决，在几个空文件内加了个{}，参考了楼下的问题。
