### ISSUE TITLE
pomelo安装问题

### ISSUE THREAD

**Issue by queentvxq** [NetEase/pomelo-cn#113]
今天帮实验室一同学安装pomelo ，报了下面的错误

``` javascript
../graph_node.cc:99:53: error: no member named 'GetRetainersCount' in
      'v8::HeapGraphNode'
  int32_t count = static_cast<HeapGraphNode*>(ptr)->GetRetainersCount();
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:132:52: error: no member named 'GetRetainedSize' in
      'v8::HeapGraphNode'
  int32_t size = static_cast<HeapGraphNode*>(ptr)->GetRetainedSize();
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:154:65: error: no member named 'GetRetainer' in
      'v8::HeapGraphNode'
  const HeapGraphEdge* edge = static_cast<HeapGraphNode*>(ptr)->GetRetainer(...
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:162:65: error: no member named 'GetDominatorNode' in
      'v8::HeapGraphNode'
  ...node = static_cast<HeapGraphNode*>(ptr)->GetDominatorNode();
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
4 errors generated.
make: *** [Release/obj.target/profiler/graph_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/v8-profiler
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok 
npm WARN optional dep failed, continuing v8-profiler@3.6.2-1
/usr/local/bin/pomelo -> /usr/local/lib/node_modules/pomelo/bin/pomelo
pomelo@0.3.3 /usr/local/lib/node_modules/pomelo
├── crc@0.2.0
├── seq-queue@0.0.5
├── pomelo-monitor@0.3.5
├── pomelo-protocol@0.1.0
├── pomelo-loader@0.0.4
├── async@0.2.5
├── mkdirp@0.3.3
├── pomelo-protobuf@0.3.0
├── pomelo-sync@0.0.3
├── pomelo-logger@0.0.2 (log4js@0.5.7)
├── pomelo-rpc@0.1.0 (stream-pkg@0.0.4, socket.io-client@0.9.11)
├── cliff@0.1.8 (eyes@0.1.8, colors@0.6.0-1, winston@0.6.2)
├── socket.io@0.9.13 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.11)
├── toobusy@0.2.2 (bindings@1.0.0)
├── ws@0.4.25 (tinycolor@0.0.1, options@0.0.3, commander@0.6.1)
└── pomelo-admin@0.1.0 (pomelo-monitor@0.3.7, pomelo-schedule@0.3.4, socket.io-client@0.9.11)
localhost:node-v0.10.0 cststu$ npm install v8-profiler
npm ERR! Error: EACCES, open '/Users/cststu/.npm/f875d38f-v8-profiler.lock'
npm ERR!  { [Error: EACCES, open '/Users/cststu/.npm/f875d38f-v8-profiler.lock']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/cststu/.npm/f875d38f-v8-profiler.lock' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "v8-profiler"
npm ERR! cwd /Users/cststu/Documents/NodeJS/NodeJS3/node-v0.10.0
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! path /Users/cststu/.npm/f875d38f-v8-profiler.lock
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, open '/Users/cststu/.npm/f875d38f-v8-profiler.lock'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/cststu/Documents/NodeJS/NodeJS3/node-v0.10.0/npm-debug.log
npm ERR! not ok code 0
localhost:node-v0.10.0 cststu$ sudo npm install v8-profiler
Password:
npm http GET https://registry.npmjs.org/v8-profiler
npm http 200 https://registry.npmjs.org/v8-profiler

> v8-profiler@3.6.2-1 install /Users/cststu/Documents/NodeJS/NodeJS3/node-v0.10.0/node_modules/v8-profiler
> node-gyp rebuild

gyp http GET http://nodejs.org/dist/v0.10.0/node-v0.10.0.tar.gz
gyp http 200 http://nodejs.org/dist/v0.10.0/node-v0.10.0.tar.gz
  CXX(target) Release/obj.target/profiler/cpu_profiler.o
  CXX(target) Release/obj.target/profiler/graph_edge.o
  CXX(target) Release/obj.target/profiler/graph_node.o
../graph_node.cc:99:53: error: no member named 'GetRetainersCount' in 'v8::HeapGraphNode'
  int32_t count = static_cast<HeapGraphNode*>(ptr)->GetRetainersCount();
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:132:52: error: no member named 'GetRetainedSize' in 'v8::HeapGraphNode'
  int32_t size = static_cast<HeapGraphNode*>(ptr)->GetRetainedSize();
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:154:65: error: no member named 'GetRetainer' in 'v8::HeapGraphNode'
  const HeapGraphEdge* edge = static_cast<HeapGraphNode*>(ptr)->GetRetainer(index);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../graph_node.cc:162:65: error: no member named 'GetDominatorNode' in 'v8::HeapGraphNode'
  const HeapGraphNode* node = static_cast<HeapGraphNode*>(ptr)->GetDominatorNode();
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
4 errors generated.
make: *** [Release/obj.target/profiler/graph_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:256:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:754:12)
gyp ERR! System Darwin 11.4.2
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/cststu/Documents/NodeJS/NodeJS3/node-v0.10.0/node_modules/v8-profiler
gyp ERR! node -v v0.10.0
gyp ERR! node-gyp -v v0.8.5
gyp ERR! not ok 
npm ERR! v8-profiler@3.6.2-1 install: `node-gyp rebuild`
npm ERR! `sh "-c" "node-gyp rebuild"` failed with 1
npm ERR! 
npm ERR! Failed at the v8-profiler@3.6.2-1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 11.4.2
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "v8-profiler"
npm ERR! cwd /Users/cststu/Documents/NodeJS/NodeJS3/node-v0.10.0
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/cststu/Documents/NodeJS/NodeJS3/node-v0.10.0/npm-debug.log
npm ERR! not ok code 0
```

node.js是源码安装的。

**Comment by py8765** [comment]
看提示是没有权限，加sudo试试。

**Comment by queentvxq** [comment]
@py8765 加sudo的，用 sudo npm install v8-profiler 报同样的错

**Comment by py8765** [comment]
看你好像是装的node的最新版本0.10.0，这个还没完全测试过，可能会有问题，因为pomelo之前一直在node 0,.8版本上测试使用。

**Comment by queentvxq** [comment]
@py8765 嗯 是最新版，哪里可以下到0.8版

**Comment by py8765** [comment]
http://nodejs.org/dist/

**Comment by sonygod** [comment]
可不可以像phpstudy一样的一键安装版，现在参考wiki上的方法安装不成功。要求另外2个环境耗时间太长了，希望有时间改进
