### ISSUE TITLE
运行demo时候的问题

### ISSUE THREAD

**Issue by zpbaaa** [NetEase/pomelo-cn#114]
我在运行lordofpemelo的时候，在本机用浏览器访问运行是正常的。
不过换成局域网里面的其他电脑来访问的话，就无法进入游戏，服务器会报错。
换成捡宝的demo，甚至pomelo init出来的新项目都会有同样的问题，这是什么原因？

[2013-03-15 14:40:49.396] [INFO] console - [2013-03-15 14:40:49.396] [ERROR] console -  Caught exception: Error: sourceEnd out of bounds
    at Buffer.copy (buffer.js:536:11)
    at copyArray (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/node_modules/pomelo-protocol/lib/protocol.js:259:11)
    at Object.Package.decode (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/node_modules/pomelo-protocol/lib/protocol.js:135:5)
    at WebSocket.Socket.state (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/lib/connectors/hybridsocket.js:32:21)
    at WebSocket.EventEmitter.emit (events.js:99:17)
    at Receiver.self._receiver.ontext (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/node_modules/ws/lib/WebSocket.js:544:10)
    at Receiver.parse (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/node_modules/ws/lib/Receiver.hixie.js:141:8)
    at doAdd (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/node_modules/ws/lib/Receiver.hixie.js:100:19)
    at Receiver.add (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/node_modules/ws/lib/Receiver.hixie.js:104:22)
    at Socket.firstHandler (/Users/zpba_mac/pomeloProject/treasures/game-server/node_modules/pomelo/node_modules/ws/lib/WebSocket.js:524:22)

**Comment by rick147** [comment]
相同问题求解决
