### ISSUE TITLE
Error: no such service:channelRemote

### ISSUE THREAD

**Issue by ETiV** [NetEase/pomelo-cn#162]
## [pushMessage] fail to dispatch msg, err:Error: no such service:channelRemote

在一个 serverHandler 中调用 channel.pushMessage 或 channelService.pushMessageByUids 时报错

``` log
[ERROR] \node_modules\pomelo\lib\common\service\channelService.js - [pushMessage] fail to dispatch msg, err:Error: no such service:channelRemote
    at Object.module.exports.route (F:\git\score-match\game-server\node_modules\pomelo\node_modules\pomelo-rpc\lib\rpc-server\dispatcher.js:20:30)
    at F:\git\score-match\game-server\node_modules\pomelo\node_modules\pomelo-rpc\lib\rpc-server\gateway.js:16:16
    at processMsg (F:\git\score-match\game-server\node_modules\pomelo\node_modules\pomelo-rpc\lib\rpc-server\acceptors\ws-acceptor.js:87:15)
    at Socket.pro.listen (F:\git\score-match\game-server\node_modules\pomelo\node_modules\pomelo-rpc\lib\rpc-server\acceptors\ws-acceptor.js:44:9)
    at Socket.EventEmitter.emit [as $emit] (events.js:96:17)
    at SocketNamespace.handlePacket (F:\git\score-match\game-server\node_modules\pomelo\node_modules\socket.io\lib\namespace.js:335:22)
    at Manager.onClientMessage (F:\git\score-match\game-server\node_modules\pomelo\node_modules\socket.io\lib\manager.js:488:38)
    at WebSocket.Transport.onMessage (F:\git\score-match\game-server\node_modules\pomelo\node_modules\socket.io\lib\transport.js:387:20)
    at Parser.<anonymous> (F:\git\score-match\game-server\node_modules\pomelo\node_modules\socket.io\lib\transports\websocket\hybi-16.js:39:10)
    at Parser.EventEmitter.emit (events.js:96:17)
```

Google 后只找到了 #32 这么个帖子, 还没详细的解决办法.-_-

无奈现在遇到这错误了, 还想知道到底是怎么回事.

我在其他的serverHandler(type/sid均不同)下调用 channelService.pushMessageByUids 是没有问题的.
能看到`pomelo-rpc/lib/rpc-server/dispatcher.js`中的 `msg.service='channelRemote'`

channel 是事先由serverRemote `get(channelName, true);` 出来的. 下面是出错的语句.

``` JavaScript
var channelService = this.app.get('channelService');
var channel = channelService.getChannel(msg.room_name, false);
if (!!channel) {
  channel.pushMessage('onUserEnterRoom', {user: session.uid}, null);
  channel.add(session.uid, this.app.getServerId());
  // ...
}
```

**Comment by GeforceLee** [comment]
我刚刚遇到这个问题，是我把addChannel的时候  把serverId 传成后端的了

**Comment by ETiV** [comment]
@GeforceLee 我汗....=.=||

**仔仔细细**看了遍API文档. channel.add()时, sid必须要frontend = true 的serverID才可以啊...
像这样
`channel.add(session.uid, session.frontendId);`
