### ISSUE TITLE
貌似64位的Windows和Ubuntu都会出问题！

### ISSUE THREAD

**Issue by py8765** [NetEase/pomelo-cn#2]
貌似64位的Windows和Ubuntu都会在编译的时候出问题！而Mountain Lion则没问题！

**Comment by py8765** [comment]
Windows 64的如下：
npm http GET https://registry.npmjs.org/async/0.1.15
profile.cc
..\snapshot.cc(90): warning C4244: “参数”: 从“uint64_t”转换到“v8::SnapshotO
bjectId”，可
能丢失数据 [C:\Users\Kaede\AppData\Roaming\npm\node_modules\pomelo\node_modules\
pome
lo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/async/0.1.15
正在创建库 C:\Users\Kaede\AppData\Roaming\npm\node_modules\pomelo\node_modu
les\
pomelo-admin\node_modules\v8-profiler\build\Release\profiler.lib 和对象 C:\Use
rs
\Kaede\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin\node
_modules\v8-profiler\build\Release\profiler.exp
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: class v8::HeapGraphN
ode cons
t \* __cdecl v8::HeapGraphNode::GetDominatorNode(void)const " (?GetDominatorNode
@HeapGraphNode@v8@@QEBAPEBV12@XZ) [C:\Users\Kaede\AppData\Roaming\npm\node_modu
les\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler.vc
xproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: class v8::HeapGraphE
dge cons
t \* __cdecl v8::HeapGraphNode::GetRetainer(int)const " (?GetRetainer@HeapGraphN
ode@v8@@QEBAPEBVHeapGraphEdge@2@H@Z) [C:\Users\Kaede\AppData\Roaming\npm\node_m
odules\pomelo\node_modules\pomelo-admin\node_modules\v8-profiler\build\profiler
.vcxproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: int __cdecl v8::Heap
GraphNod
e::GetRetainersCount(void)const " (?GetRetainersCount@HeapGraphNode@v8@@QEBAHXZ
) [C:\Users\Kaede\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-a
dmin\node_modules\v8-profiler\build\profiler.vcxproj]
graph_node.obj : error LNK2001: 无法解析的外部符号 "public: int __cdecl v8::Heap
GraphNod
e::GetRetainedSize(void)const " (?GetRetainedSize@HeapGraphNode@v8@@QEBAHXZ) [C
:\Users\Kaede\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admin
\node_modules\v8-profiler\build\profiler.vcxproj]
C:\Users\Kaede\AppData\Roaming\npm\node_modules\pomelo\node_modules\pomelo-admi
n\node_modules\v8-profiler\build\Release\profiler.node : fatal error LNK1120: 4
个无法解析的外部命令 [C:\Users\Kaede\AppData\Roaming\npm\node_modules\pomelo\no
de_module
s\pomelo-admin\node_modules\v8-profiler\build\profiler.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:236:23)
gyp ERR! stack at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Kaede\AppData\Roaming\npm\node_modules\pomelo\node_modules
\pomelo-admin\node_modules\v8-profiler
gyp ERR! node -v v0.8.14
gyp ERR! node-gyp -v v0.7.1
gyp ERR! not ok
npm ERR! v8-profiler@3.6.2-1 install: node-gyp rebuild
npm ERR! cmd "/c" "node-gyp rebuild" failed with 1
npm ERR!
npm ERR! Failed at the v8-profiler@3.6.2-1 install script.
npm ERR! This is most likely a problem with the v8-profiler package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get their info via:
npm ERR! npm owner ls v8-profiler
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "pomelo" "-g"
npm ERR! cwd C:\
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! code ELIFECYCLE
npm ERR! Error: EPERM, open 'C:\npm-debug.log'
npm ERR! { [Error: EPERM, open 'C:\npm-debug.log'] errno: 50, code: 'EPERM', pa
th: 'C:\npm-debug.log' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "pomelo" "-g"
npm ERR! cwd C:\
npm ERR! node -v v0.8.14
npm ERR! npm -v 1.1.65
npm ERR! path C:\npm-debug.log
npm ERR! code EPERM
npm ERR! errno 50
npm ERR! stack Error: EPERM, open 'C:\npm-debug.log'
npm http 304 https://registry.npmjs.org/tinycolor
npm http 408 https://registry.npmjs.org/commander
npm ERR! registry error parsing json
npm http GET https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/commander
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! C:\npm-debug.log
npm ERR! not ok code 0

**Comment by py8765** [comment]
这个异常是V8-profiler编译的问题， 试一下npm install v8-profiler， 看看会不会出问题。
我们会计划在下个版本支持windows
