### ISSUE TITLE
这个是什么原因啊？在win7环境下

### ISSUE THREAD

**Issue by yangyang880402** [NetEase/pomelo-cn#200]
"C:\Program Files\nodejs\node.exe" app.js env=development

module.js:340
    throw err;
          ^
Error: Cannot find module 'crc'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\yangyang\AppData\Roaming\npm\chatofpomelo\game-server\app\util\dispatcher.js:1:73)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

Process finished with exit code 8

**Comment by py8765** [comment]
看报错是找不到crc模块，npm install 安装一下。

**Comment by Douzy** [comment]
npm install -d

**Comment by Hakunata** [comment]
@py8765 我git下来chatofpomelo-websockets 运行也报这个错误，按照你的方法：npm install后，还是不行。不知道楼主的问题解决了没有？求答复 ：）

**Comment by py8765** [comment]
我在win7上单独npm install crc是没有问题的，你先npm cache clean一下，再不行就单独安装crc再把它拷贝到game-server/npm-modules/下面。

**Comment by Hakunata** [comment]
下午弄好了，应该是我git项目下来后，没有在工程目录sh npm-install.sh。
