### ISSUE TITLE
masterAgent 报错：Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by leeboo** [NetEase/pomelo-cn#230]
[2014-02-20 10:40:31.326] [ERROR] process - [31m137: [master] [1057] [39muncaughtException in server master-server-1(1057)  {}，TypeError: Cannot read property 'info' of undefined
    at removeConnection (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-admin/lib/masterAgent.js:577:23)
    at Socket.<anonymous> (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-admin/lib/masterAgent.js:234:9)
    at Socket.EventEmitter.emit [as $emit](events.js:95:17)
    at Socket.onDisconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/socket.js:153:10)
    at SocketNamespace.handleDisconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/namespace.js:229:46)
    at Manager.onClientDisconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/manager.js:501:29)
    at WebSocket.Transport.end (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/transport.js:467:20)
    at WebSocket.Transport.onSocketEnd (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/transport.js:147:8)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by leeboo** [comment]
日志中出现的许多这个错误，整体分布式的游戏服务器集群不能正常工作，这是什么原因啊

**Comment by py8765** [comment]
看报错好像对应的pomelo-admin的版本比较老，pomelo用的什么版本？

**Comment by leeboo** [comment]
Pomelo 0.8 
Pomelo-admin 0.2.7
