### ISSUE TITLE
我们分布式部署pomelo，运行一段时间后经常出现下面的错误

### ISSUE THREAD

**Issue by leeboo** [NetEase/pomelo-cn#231]
[2014-02-21 21:41:18.585] [ERROR] process - [31m142: [spidertimer] [1132] [39muncaughtException in server spidertimer-server-1(1132)  {}，TypeError: Cannot read property 'length' of undefined
    at flushPending (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:367:14)
    at /var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:344:5
    at Object.exp.invokeCallback (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/util/utils.js:5:8)
    at SocketNamespace.<anonymous> (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js:62:11)
    at SocketNamespace.EventEmitter.emit [as $emit](/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/events.js:165:15)
    at SocketNamespace.onPacket (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/namespace.js:152:14)
    at Socket.onPacket (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/socket.js:443:30)
    at Transport.onPacket (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/transport.js:98:17)
    at Transport.onData (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/transport.js:69:16)
    at WebSocket.websocket.onmessage (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/transports/websocket.js:73:12)
    at WebSocket.onMessage (/var/www/game/game-server/node_modules/pomelo/node_modules/ws/lib/WebSocket.js:321:18)

[2014-02-21 21:10:08.126] [ERROR] process - [31m142: [spidertimer] [1132] [39muncaughtException in server spidertimer-server-1(1132)  {}，TypeError: Cannot call method 'close' of undefined
    at Socket.onDisconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/socket.js:480:22)
    at Socket.disconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/socket.js:346:12)
    at SocketNamespace.disconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/namespace.js:124:19)
    at pro.close (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js:91:15)
    at pro.removeServer (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:139:13)
    at pro.removeServers (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:155:10)
    at pro.removeServers (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/client.js:149:17)
    at pro.removeServers (/var/www/game/game-server/node_modules/pomelo/lib/components/proxy.js:118:15)
    at EventEmitter.emit (events.js:95:17)
    at Object.Application.removeServers (/var/www/game/game-server/node_modules/pomelo/lib/application.js:813:14)

[2014-02-20 11:54:13.829] [ERROR] process - [31m137: [master] [1057] [39muncaughtException in server master-server-1(1057)  {}，TypeError: Cannot read property 'info' of undefined
    at removeConnection (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-admin/lib/masterAgent.js:577:23)
    at Socket.<anonymous> (/var/www/game/game-server/node_modules/pomelo/node_modules/pomelo-admin/lib/masterAgent.js:234:9)
    at Socket.EventEmitter.emit [as $emit](events.js:95:17)
    at Socket.onDisconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/socket.js:153:10)
    at SocketNamespace.handleDisconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/namespace.js:229:46)
    at Manager.onClientDisconnect (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/manager.js:501:29)
    at WebSocket.Transport.end (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/transport.js:467:20)
    at WebSocket.Transport.onSocketEnd (/var/www/game/game-server/node_modules/pomelo/node_modules/socket.io/lib/transport.js:147:8)
    at Socket.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)

**Comment by shuhuiguo** [comment]
我也碰到了这问题，请问有解决吗？解决方式是啥？
