### ISSUE TITLE
求救，部署最新版本聊天应用的错误

### ISSUE THREAD

**Issue by mani95lisa** [NetEase/pomelo-cn#239]
```
[2014-03-29 11:51:34.926] [DEBUG] pomelo - [/var/local/chatofpomelo/game-server/node_modules/pomelo/lib/components/connector.js] session on [connector-server-3] bind with uid: 22*2

[2014-03-29 11:51:37.926] [WARN] pomelo - [/var/local/chatofpomelo/game-server/node_modules/pomelo/lib/filters/handler/timeout.js] request "connector.entryHandler.enter" timeout.

[2014-03-29 11:52:37.942] [ERROR] console -  Caught exception: Error: fail to connect to remote server: chat-server-2
    at /var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailstation.js:349:29
    at Object.exp.invokeCallback (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/util/utils.js:5:8)
    at SocketNamespace.<anonymous> (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-client/mailboxes/ws-mailbox.js:69:11)
    at SocketNamespace.EventEmitter.emit [as $emit] (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/events.js:165:15)
    at Socket.publish (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/socket.js:103:19)
    at Socket.onError (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/socket.js:462:10)
    at xhr.onreadystatechange (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/lib/socket.js:165:40)
    at dispatchEvent (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:519:25)
    at setState (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:538:14)
    at handleError (/var/local/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:463:5)

```

**Comment by mani95lisa** [comment]
已解决，因为之前不需要开启的4050之类的端口没有开启
