### ISSUE TITLE
Helloworld就报错

### ISSUE THREAD

**Issue by MxBird** [NetEase/pomelo-cn#252]
安装什么的都是按照教程来的。
启动game-server也是正常的，
但是网页点击test server后台就报错  

```
[2014-08-25 16:20:47.189] [ERROR] console -  Caught exception: TypeError: Cannot convert undefined or null to object
    at copyArray (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/node_modules/pomelo-protocol/lib/protocol.js:266:11)
    at Object.Package.decode (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/node_modules/pomelo-protocol/lib/protocol.js:138:7)
    at WebSocket.<anonymous> (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/lib/connectors/hybridsocket.js:40:21)
    at WebSocket.EventEmitter.emit (events.js:110:17)
    at Receiver.self._receiver.onbinary (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/node_modules/ws/lib/WebSocket.js:549:10)
    at Receiver.opcodes.2.finish (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/node_modules/ws/lib/Receiver.js:448:14)
    at Receiver.expectHandler (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/node_modules/ws/lib/Receiver.js:433:33)
    at Receiver.add (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/node_modules/ws/lib/Receiver.js:93:24)
    at Socket.firstHandler (/Users/Ray/Project/personal/sandbox/hello/game-server/node_modules/pomelo/node_modules/ws/lib/WebSocket.js:524:22)
    at Socket.EventEmitter.emit (events.js:107:17)
```

**Comment by MxBird** [comment]
使用的是 pomelo 1.0.3

**Comment by MxBird** [comment]
浏览器使用的chrome最新版本的 支持websocket

**Comment by MxBird** [comment]
解决了  更换到一个老一点的node版本就可以了。
