### ISSUE TITLE
linux安装pomelo不成功

### ISSUE THREAD

**Issue by w1ng** [NetEase/pomelo-cn#266]
node版本是v0.10.25,
gcc版本是gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2,
npm版本是1.3.10,
执行sudo npm install -g pomelo报错. 日志如下:

npm http GET https://registry.npmjs.org/pomelo
npm http GET https://registry.npmjs.org/pomelo
npm http GET https://registry.npmjs.org/pomelo
npm http 304 https://registry.npmjs.org/pomelo
npm http GET https://registry.npmjs.org/socket.io/0.9.16
npm http GET https://registry.npmjs.org/async/0.2.5
npm http GET https://registry.npmjs.org/pomelo-protocol/0.1.6
npm http GET https://registry.npmjs.org/pomelo-admin/0.4.5
npm http GET https://registry.npmjs.org/mkdirp/0.3.3
npm http GET https://registry.npmjs.org/pomelo-scheduler/0.3.9
npm http GET https://registry.npmjs.org/pomelo-loader/0.0.6
npm http GET https://registry.npmjs.org/pomelo-logger/0.1.7
npm http GET https://registry.npmjs.org/crc/0.2.0
npm http GET https://registry.npmjs.org/ws/0.8.0
npm http GET https://registry.npmjs.org/pomelo-protobuf/0.4.0
npm http GET https://registry.npmjs.org/commander/2.0.0
npm http GET https://registry.npmjs.org/mqtt/0.3.9
npm http GET https://registry.npmjs.org/node-bignumber/1.2.1
npm http GET https://registry.npmjs.org/seq-queue/0.0.5
npm http GET https://registry.npmjs.org/cliff/0.1.8
npm http GET https://registry.npmjs.org/pomelo-rpc/0.4.10
npm http 304 https://registry.npmjs.org/pomelo-admin/0.4.5
npm http 200 https://registry.npmjs.org/async/0.2.5
npm http GET https://registry.npmjs.org/async/-/async-0.2.5.tgz
npm http 304 https://registry.npmjs.org/socket.io/0.9.16
npm http 304 https://registry.npmjs.org/mkdirp/0.3.3
npm http 304 https://registry.npmjs.org/pomelo-scheduler/0.3.9
npm http 304 https://registry.npmjs.org/pomelo-protocol/0.1.6
npm http 304 https://registry.npmjs.org/crc/0.2.0
npm http 304 https://registry.npmjs.org/ws/0.8.0
npm http 304 https://registry.npmjs.org/pomelo-loader/0.0.6
npm http 304 https://registry.npmjs.org/pomelo-logger/0.1.7
npm http 304 https://registry.npmjs.org/pomelo-protobuf/0.4.0
npm http 200 https://registry.npmjs.org/async/-/async-0.2.5.tgz
npm http 304 https://registry.npmjs.org/cliff/0.1.8
npm http 200 https://registry.npmjs.org/mqtt/0.3.9
npm http GET https://registry.npmjs.org/mqtt/-/mqtt-0.3.9.tgz
npm http 200 https://registry.npmjs.org/commander/2.0.0
npm http GET https://registry.npmjs.org/commander/-/commander-2.0.0.tgz
npm http 304 https://registry.npmjs.org/node-bignumber/1.2.1
npm http 304 https://registry.npmjs.org/seq-queue/0.0.5
npm http 304 https://registry.npmjs.org/pomelo-rpc/0.4.10
npm http 200 https://registry.npmjs.org/commander/-/commander-2.0.0.tgz
npm http 200 https://registry.npmjs.org/mqtt/-/mqtt-0.3.9.tgz
npm http GET https://registry.npmjs.org/log4js/0.6.21
npm http GET https://registry.npmjs.org/log4js/0.6.7
npm http GET https://registry.npmjs.org/bufferutil
npm http GET https://registry.npmjs.org/utf-8-validate
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/heapdump/0.3.7
npm http GET https://registry.npmjs.org/pomelo-scheduler/0.3.8
npm http GET https://registry.npmjs.org/pomelo-monitor/0.3.7
npm http GET https://registry.npmjs.org/socket.io-client/0.9.16
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http GET https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/base64id/0.1.0
npm http GET https://registry.npmjs.org/winston
npm http GET https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/bops
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/node-uuid/1.4.0
npm http GET https://registry.npmjs.org/stream-pkg/0.0.5
npm http GET https://registry.npmjs.org/async/0.2.10
npm http 304 https://registry.npmjs.org/log4js/0.6.7
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/utf-8-validate
npm http 304 https://registry.npmjs.org/bufferutil
npm ERR! tar.unpack untar error /root/.npm/log4js/0.6.7/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js'
npm ERR! error rolling back  log4js@0.6.7 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js' }
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js/.bob/instrumented/lib/connect-logger.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js/.bob/instrumented/lib/connect-logger.js
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-scheduler/node_modules/log4js/.bob/instrumented/lib/connect-logger.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/log4js/0.6.21
npm ERR! Error: unexpected eof
npm ERR!     at decorate (/usr/lib/nodejs/fstream/lib/abstract.js:67:36)
npm ERR!     at Extract.Abstract.error (/usr/lib/nodejs/fstream/lib/abstract.js:61:12)
npm ERR!     at Extract._streamEnd (/usr/lib/nodejs/tar/lib/extract.js:75:22)
npm ERR!     at BlockStream.<anonymous> (/usr/lib/nodejs/tar/lib/parse.js:50:8)
npm ERR!     at BlockStream.EventEmitter.emit (events.js:92:17)
npm ERR!     at BlockStream._emitChunk (/usr/lib/nodejs/block-stream.js:203:10)
npm ERR!     at BlockStream.resume (/usr/lib/nodejs/block-stream.js:58:15)
npm ERR!     at Extract.Reader.resume (/usr/lib/nodejs/fstream/lib/reader.js:252:34)
npm ERR!     at Entry.<anonymous> (/usr/lib/nodejs/tar/lib/parse.js:256:8)
npm ERR!     at Entry.EventEmitter.emit (events.js:92:17)
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! fstream_class Extract
npm ERR! fstream_stack Extract._streamEnd (/usr/lib/nodejs/tar/lib/extract.js:75:22)
npm ERR! fstream_stack BlockStream.<anonymous> (/usr/lib/nodejs/tar/lib/parse.js:50:8)
npm ERR! fstream_stack BlockStream.EventEmitter.emit (events.js:92:17)
npm ERR! fstream_stack BlockStream._emitChunk (/usr/lib/nodejs/block-stream.js:203:10)
npm ERR! fstream_stack BlockStream.resume (/usr/lib/nodejs/block-stream.js:58:15)
npm ERR! fstream_stack Extract.Reader.resume (/usr/lib/nodejs/fstream/lib/reader.js:252:34)
npm ERR! fstream_stack Entry.<anonymous> (/usr/lib/nodejs/tar/lib/parse.js:256:8)
npm ERR! fstream_stack Entry.EventEmitter.emit (events.js:92:17)
npm http 304 https://registry.npmjs.org/ultron
npm http GET https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/pomelo-monitor/0.3.7
npm http GET https://registry.npmjs.org/semver
npm http 200 https://registry.npmjs.org/redis/0.7.3
npm http GET https://registry.npmjs.org/redis/-/redis-0.7.3.tgz
npm http 304 https://registry.npmjs.org/socket.io-client/0.9.16
npm http 304 https://registry.npmjs.org/heapdump/0.3.7
npm http 304 https://registry.npmjs.org/pomelo-scheduler/0.3.8

> heapdump@0.3.7 install /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
> node-gyp rebuild

npm http 304 https://registry.npmjs.org/colors
npm http 304 https://registry.npmjs.org/winston
npm http 304 https://registry.npmjs.org/eyes
npm http GET https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/base64id/0.1.0
npm http 304 https://registry.npmjs.org/bops
npm http GET https://registry.npmjs.org/stack-trace
npm http GET https://registry.npmjs.org/cycle
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/pkginfo
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/base64-js/0.0.2
npm http GET https://registry.npmjs.org/to-utf8/0.0.1
npm http 304 https://registry.npmjs.org/bindings
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm http 304 https://registry.npmjs.org/stream-pkg/0.0.5
npm http 304 https://registry.npmjs.org/nan
npm http 200 https://registry.npmjs.org/async/0.2.10
npm http GET https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http 304 https://registry.npmjs.org/node-uuid/1.4.0

> bufferutil@1.2.1 install /usr/local/lib/node_modules/pomelo/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

npm http 200 https://registry.npmjs.org/redis/-/redis-0.7.3.tgz
npm http 304 https://registry.npmjs.org/semver
npm http 304 https://registry.npmjs.org/log4js
npm http 304 https://registry.npmjs.org/stack-trace
npm http 304 https://registry.npmjs.org/cycle
npm http 304 https://registry.npmjs.org/pkginfo
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/core-util-is

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/pomelo/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory `/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump/build'
npm http 304 https://registry.npmjs.org/string_decoder
  CXX(target) Release/obj.target/addon/src/heapdump.o
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/isarray/0.0.1
make: Entering directory`/usr/local/lib/node_modules/pomelo/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
npm http 304 https://registry.npmjs.org/ws
npm http 200 https://registry.npmjs.org/async
npm http 200 https://registry.npmjs.org/async/-/async-0.2.10.tgz
npm http 200 https://registry.npmjs.org/request
npm http 304 https://registry.npmjs.org/base64-js/0.0.2
npm http 304 https://registry.npmjs.org/to-utf8/0.0.1
npm http GET https://registry.npmjs.org/semver/-/semver-4.3.6.tgz
npm http GET https://registry.npmjs.org/underscore/1.8.2
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
npm ERR! tar.unpack untar error /root/.npm/uglify-js/1.2.5/package.tgz
npm ERR! tar.unpack untar error /root/.npm/uglify-js/1.2.5/package.tgz
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/xmlhttprequest/lib/XMLHttpRequest.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
make: Entering directory `/usr/local/lib/node_modules/pomelo/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client'
npm ERR! error rolling back  socket.io-client@0.9.16 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client' }
npm http 304 https://registry.npmjs.org/underscore/1.8.2
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/ws/lib/BufferPool.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/ws/lib/BufferPool.js
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/socket.io-client/node_modules/ws/lib/BufferPool.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/semver/-/semver-4.3.6.tgz
npm http GET https://registry.npmjs.org/underscore/-/underscore-1.8.2.tgz
npm http 200 https://registry.npmjs.org/underscore/-/underscore-1.8.2.tgz
../src/heapdump.cc:175:1: fatal error: opening dependency file ./Release/.deps/Release/obj.target/addon/src/heapdump.o.d.raw: No such file or directory
compilation terminated.
Cannot create temporary file in /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump/: No such file or directory
make: **\* [Release/obj.target/addon/src/heapdump.o] Aborted
make: Leaving directory `/usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump/build'
gyp ERR! build error 
gyp ERR! stack Error:`make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.0-32-generic
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/pomelo/node_modules/pomelo-admin/node_modules/heapdump
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/uglify-js/1.2.5
npm http GET https://registry.npmjs.org/ws
npm http GET https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http GET https://registry.npmjs.org/active-x-obfuscator/0.0.1
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/validation.node
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.4.2
npm http 304 https://registry.npmjs.org/active-x-obfuscator/0.0.1
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
  COPY Release/bufferutil.node
make: Leaving directory `/usr/local/lib/node_modules/pomelo/node_modules/ws/node_modules/utf-8-validate/build'
make: Leaving directory`/usr/local/lib/node_modules/pomelo/node_modules/ws/node_modules/bufferutil/build'
npm http 304 https://registry.npmjs.org/uglify-js/1.2.5
npm ERR! tar.unpack untar error /root/.npm/uglify-js/1.2.5/package.tgz
npm ERR! tar.unpack untar error /root/.npm/uglify-js/1.2.5/package.tgz
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! tar.unpack untar error /root/.npm/uglify-js/1.2.5/package.tgz
npm http GET https://registry.npmjs.org/zeparser/0.0.5
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client'
npm ERR! error rolling back  socket.io-client@0.9.16 { [Error: ENOTEMPTY, rmdir '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client' }
npm ERR! tar.unpack untar error /root/.npm/uglify-js/1.2.5/package.tgz
npm ERR! Error: ENOENT, chown '/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/active-x-obfuscator'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/active-x-obfuscator
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/active-x-obfuscator
npm ERR! fstream_type Directory
npm ERR! fstream_class DirWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/usr/local/lib/node_modules/pomelo/node_modules/socket.io/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs'
npm ERR! If you need help, you may report this log at:
npm ERR!     http://github.com/isaacs/npm/issues
npm ERR! or email it to:
npm ERR!     npm-@googlegroups.com

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "pomelo"
npm ERR! cwd /root
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path /usr/local/lib/node_modules/pomelo/node_modules/socket.io/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs
npm ERR! fstream_path /usr/local/lib/node_modules/pomelo/node_modules/socket.io/node_modules/socket.io-client/node_modules/uglify-js/bin/uglifyjs
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/zeparser/0.0.5
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/nan
npm http GET https://registry.npmjs.org/options
npm http GET https://registry.npmjs.org/tinycolor
npm http 304 https://registry.npmjs.org/options
npm http 304 https://registry.npmjs.org/nan
npm http 304 https://registry.npmjs.org/tinycolor
npm http 200 https://registry.npmjs.org/commander

> ws@0.4.32 install /usr/local/lib/node_modules/pomelo/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)
> 
> ws@0.4.32 install /usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/usr/local/lib/node_modules/pomelo/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
make: Entering directory`/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
  COPY Release/validation.node
make: Leaving directory `/usr/local/lib/node_modules/pomelo/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
make: Leaving directory`/usr/local/lib/node_modules/pomelo/node_modules/pomelo-rpc/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log
npm ERR! not ok code 0

**Comment by jiangzhuo** [comment]
304错误 没有吓到要的package所以untar的时候没有东西解压报错了
首先清缓存
然后请在良好的能正常链接国际互联网的环境下安装
