### ISSUE TITLE
pomelo运行官方聊天示例客户端连接时服务器会报错？求解,运行环境win7

### ISSUE THREAD

**Issue by chinablank** [NetEase/pomelo-cn#275]
[2018-03-02 17:43:40.246] [ERROR] console - Caught exception: TypeError: ParserIncomingMessage is not a constructor
at HTTPParser.parserOnHeadersComplete (http_common.js:81:21)
at socketOnData (http_server.js:472:20)
at Socket.emit (events.js:127:13)
at Processor.add (E:\chatofpomelo-websocket-master\game-server\node_modules\pomelo\lib\connectors\hybrid\wsprocessor.js:40:12)
at processHttp (E:\chatofpomelo-websocket-master\game-server\node_modules\pomelo\lib\connectors\hybrid\switcher.js:98:13)
at Socket.<anonymous> (E:\chatofpomelo-websocket-master\game-server\node_modules\pomelo\lib\connectors\hybrid\switcher.js:65:7)
at Object.onceWrapper (events.js:219:13)
at Socket.emit (events.js:127:13)
at addChunk (stream_readable.js:269:12)
at readableAddChunk (stream_readable.js:256:11)

**Comment by chinablank** [comment]
是因为协议问题吗？之前helloworld的示例也会这样，后来协议选择由websocket改成socket.io就没问题了
