### ISSUE TITLE
Pomelo list 还是报错

### ISSUE THREAD

**Issue by jwkfreedom** [NetEase/pomelo-cn#29]
Pomelo list 还是报错。已经获得最新代码了。
有logs目录，logs目录下有tmp文件。

报错如下:
F:\webserver\pomelo\test\helloworld>pomelo list

C:\Users\jwk\AppData\Roaming\npm\node_modules\pomelo\bin\pomelo:211
              rows.push([server['serverId'], server['serverType'], server['pid
                               ^
TypeError: Cannot read property 'serverId' of null
    at C:\Users\jwk\AppData\Roaming\npm\node_modules\pomelo\bin\pomelo:211:32
    at SocketNamespace.Client.connect (C:\Users\jwk\AppData\Roaming\npm\node_mod
ules\pomelo\node_modules\pomelo-admin\lib\client\client.js:45:6)
    at SocketNamespace.EventEmitter.emit [as $emit](C:UsersjwkAppDataRoamin
gnpmnode_modulespomelonode_modulespomelo-adminnode_modulessocket.io-clien
tlibevents.js:165:15)
    at SocketNamespace.onPacket (C:\Users\jwk\AppData\Roaming\npm\node_modules\p
omelo\node_modules\pomelo-admin\node_modules\socket.io-client\lib\namespace.js:1
82:20)
    at Socket.onPacket (C:\Users\jwk\AppData\Roaming\npm\node_modules\pomelo\nod
e_modules\pomelo-admin\node_modules\socket.io-client\lib\socket.js:443:30)
    at Transport.onPacket (C:\Users\jwk\AppData\Roaming\npm\node_modules\pomelo\
node_modules\pomelo-admin\node_modules\socket.io-client\lib\transport.js:98:17)
    at Transport.onData (C:\Users\jwk\AppData\Roaming\npm\node_modules\pomelo\no
de_modules\pomelo-admin\node_modules\socket.io-client\lib\transport.js:69:16)
    at WebSocket.WS.open.websocket.onmessage (C:\Users\jwk\AppData\Roaming\npm\n
ode_modules\pomelo\node_modules\pomelo-admin\node_modules\socket.io-client\lib\t
ransports\websocket.js:73:12)
    at WebSocket.onMessage (C:\Users\jwk\AppData\Roaming\npm\node_modules\pomelo
\node_modules\pomelo-admin\node_modules\socket.io-client\node_modules\ws\lib\Web
Socket.js:321:18)
    at WebSocket.EventEmitter.emit (events.js:99:17)

另外, game server报错如下: 
getPsInfo failed! Error: Command failed: ‘ps'
   at ChildProcess.exithandler<child_process.js:540:15>

**Comment by py8765** [comment]
嗯，之前是github上已经更新，但是还没有上传到npm上，现在已经好了，请更新到0.2.4版本。
