### ISSUE TITLE
有关发消息给同一个channel的问题

### ISSUE THREAD

**Issue by NewYuil** [NetEase/pomelo-cn#32]
我想要实现在同一个channel里的玩家互相通信，程序是照着chatofpomelo写的，但出错了，出错信息如下：
[2013-01-05 20:43:15.154] [INFO] console - [2013-01-05 20:43:15.083] [ERROR] /node_modules/pomelo/lib/common/service/channelService.js - [pushMessage] fail to dispatch msg, err:Error: no such service:channelRemote
    at Object.module.exports.route (/Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/dispatcher.js:19:28)
    at /Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/gateway.js:16:14
    at processMsg (/Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/acceptors/ws-acceptor.js:87:14)
    at Socket.pro.listen (/Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/pomelo-rpc/lib/rpc-server/acceptors/ws-acceptor.js:44:5)
    at Socket.EventEmitter.emit [as $emit](events.js:96:17)
    at SocketNamespace.handlePacket (/Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/socket.io/lib/manager.js:488:38)
    at WebSocket.Transport.onMessage (/Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/Users/liu/Documents/wsspace/chatofpomelo/game-server/node_modules/pomelo/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
    at Parser.EventEmitter.emit (events.js:96:17)

我调试后发现是下面这条语言出错了。app.rpcInvoke
其中：namespace='sys'  service='channelRemote'  method="pushMessage",args=[Array]  msg="{"route":"onAdd","user":"lwy"}"   uids=[liu*1]

```
   for(var sid in groups) {
    var uids = groups[sid];
    app.rpcInvoke(sid, {namespace: namespace, service: service, method: method, args: [msg, uids]}, function(err) {
        if(err) {
            logger.error('[pushMessage] fail to dispatch msg, err:' + err.stack);
            latch.done();
            return;
        }
        successFlag = true;
        latch.done();
    });
}
```

这问题怎么解决啊？

**Comment by NewYuil** [comment]
找到问题的原因了，是sid设置错了，前段服务器的id设置错了
