### ISSUE TITLE
监控模块报错Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#43]
[2013-01-13 19:31:02.319] [ERROR] console -  Caught exception: TypeError: Cannot read property 'length' of undefined
    at list (/home/Hengstar/workspace/Epic_Servers/Epic-Pomelo/game-server/node_modules/pomelo/node_modules/pomelo-admin/lib/modules/scripts.js:78:33)
    at Object.oncomplete (fs.js:297:15)

在打开监控后，监控页面中选择request中的节点就会报以上错误，为啥？

**Comment by piaohai** [comment]
应用是scriptModule.root这个目录传入不正确或者目录不存在

**Comment by gongxinheng** [comment]
这个值是根据什么确定的？应该不是我手动传入的

**Comment by piaohai** [comment]
你在game-server建scripts这个目录试一下。
