### ISSUE TITLE
关于Pomelo的调试问题

### ISSUE THREAD

**Issue by gongxinheng** [NetEase/pomelo-cn#8]
调试过程中经常遇到类似这样的错误
[2012-12-19 13:47:55.100] [INFO] console - [2012-12-19 13:47:55.099] [ERROR] console -  Caught exception: TypeError: Cannot call method 'findById' of undefined
    at new Player (/home/Hengstar/workspace/Epic_Servers/Epic-Pomelo/game-server/app/domain/entity/player.js:45:32)
    at userDao.getPlayer (/home/Hengstar/workspace/Epic_Servers/Epic-Pomelo/game-server/app/dao/userDao.js:80:34)
但是不知道具体是哪个服务器或哪个进程报出的，所以往往挂接了好几个调试器还是没有找到。有什么办法能方便的得知错误出自哪吗？

**Comment by gongxinheng** [comment]
另外再问个问题，我想调试某个服务器初始化的接口。不知道Pomelo有没有提供单个服务器设置启动暂停等待调试器挂接的功能呢？

**Comment by gongxinheng** [comment]
额，调试找到解决方法了。手动启动单个服务器，例如如下指令。
cd /home/user/workspace/Pomelo/game-server && node --debug-brk /home/user/workspace/Pomelo/game-server/app.js env=development serverType=area serverId=area-server-1 locally
再挂接调试器就可以了

**Comment by py8765** [comment]
如果想确切知道哪台服务器报错，可以查看game-server/logs目录下不同的日志文件。其实对于不同服务器而言，代码都是同一份，而且如果是单机运行就直接在代码中进行调试即可。

**Comment by gongxinheng** [comment]
了解了~谢谢！
