### ISSUE TITLE
pomelo start出错

### ISSUE THREAD

**Issue by innobeanslong** [NetEase/pomelo-cn#97]
Error: /root/long/work/SLGServer/GameServer/game-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/v8-profiler/build/Release/profiler.node: invalid ELF header
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/root/long/work/SLGServer/GameServer/game-server/node_modules/pomelo/node_modules/pomelo-admin/node_modules/v8-profiler/v8-profiler.js:1:77)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
这是提示报错的内容，求大神帮忙看下~

**Comment by py8765** [comment]
什么版本的pomelo，在windows下跑的吗

**Comment by innobeanslong** [comment]
centOS的虚拟机，0.2版本的，年前还一直用来着，今天启动的时候发现不能用了，mac下同样版本的代码没什么问题

**Comment by py8765** [comment]
把依赖先删掉，更新到0.2.5，npm把缓存清理一下，重新安装依赖，再试试。

**Comment by innobeanslong** [comment]
非常感谢，按照您说的步骤试了下，可以正常启动了
